@startmindmap
* __do_global_dtors_aux
** deregister_tm_clones
* frame_dummy
** register_tm_clones
* SVC_Handler
* DebugMon_Handler
* PendSV_Handler
* SysTick_Handler
** HAL_IncTick
** my_function#2
*** HAL_GPIO_WritePin
*** HAL_Delay
**** HAL_GetTick
**** HAL_GetTick
* RCC_Delay
* Reset_Handler
** SystemInit
** LoopCopyDataInit
*** CopyDataInit
*** LoopFillZerobss
**** FillZerobss
**** __libc_init_array
***** _init
**** main
***** HAL_Init
****** HAL_NVIC_SetPriorityGrouping
****** HAL_InitTick
******* HAL_SYSTICK_Config
******* HAL_NVIC_SetPriority
******** NVIC_EncodePriority
******** __NVIC_SetPriority
****** HAL_MspInit
******* my_function#3
******** HAL_GPIO_WritePin
***** SystemClock_Config
****** memset
****** HAL_RCC_OscConfig
****** HAL_RCC_ClockConfig
******* HAL_GetTick
******* HAL_GetTick
******* HAL_RCC_GetSysClockFreq
******* HAL_InitTick
******** HAL_SYSTICK_Config
******** HAL_NVIC_SetPriority
********* NVIC_EncodePriority
********* __NVIC_SetPriority
****** Error_Handler
****** Error_Handler
***** MX_GPIO_Init
****** HAL_GPIO_WritePin
****** HAL_GPIO_Init
***** my_function
****** HAL_GPIO_WritePin
****** HAL_Delay
******* HAL_GetTick
******* HAL_GetTick
****** HAL_GPIO_WritePin
****** HAL_Delay
******* HAL_GetTick
******* HAL_GetTick
@endmindmap
